### ISSUE TITLE
Volunteers Wizard 'Parent Campaign ID' lookup popup is incomplete

### ISSUE THREAD

**Issue by chrismcmahon** [SalesforceFoundation/Volunteers-for-Salesforce#240]
I created a Campaign called 'deleteme'

On the regular Salesforce non-Lightning Campaign tab, I click 'New'. I click the lookup box for Parent Campaign and I get a popup box with a select list containing choices for "My Active Campaigns" and three other choices, including "All Campaigns".  When I choose "All Campaigns" I can see the "deleteme" Campaign I created. 

![screen shot 2016-12-27 at 2 53 21 pm](https://cloud.githubusercontent.com/assets/204643/21509234/5487e96e-cc44-11e6-8244-f8acf5fbe09f.png)

From the Volunteers Wizard page, when I click the lookup box for Parent Campaign, the resulting popup box does not contain the select list for "My Active Campaigns" etc. I cannot choose "All Campaigns" and I cannot make my 'deleteme' Campaign the parent of a Volunteers Wizard-created Campaign. 

![screen shot 2016-12-27 at 2 53 45 pm](https://cloud.githubusercontent.com/assets/204643/21509273/a1588ff0-cc44-11e6-9cd0-4f8875a25ba0.png)

**Comment by davidhabib** [comment]
**lurch: add

**Comment by davidhabib** [comment]
Salesforce handles the popup, but we should understand why this no longer works.  by no longer including standard aloha style sheets, this is broken.  can any additional markup we can add get this back?

**Comment by LurchTheButler** [comment]
Tracking <a href="https://foundation.my.salesforce.com/a2x80000004PkCjAAK" target="_blank">W-017299</a>

**Comment by cdcarter** [comment]
I believe this is default (undocumented) Visualforce behavior for the Campaign lookup. For example:

`<apex:page standardController="Campaign">
    <apex:form>
        <apex:pageBlock>
        <apex:pageBlockSection>
                    <apex:inputField value="{!Campaign.ParentId}"/>
            </apex:pageBlockSection>
        </apex:pageBlock>
    </apex:form>
</apex:page>`

runs into the same issue, despite not using lightning styling.

However, since we have control over the page, a little javascript hacking can get you there:

`elem.href.replace('lkfm','overrideScope%3D1%26enableNew%3D1%26enableScopes%3D1%26extendedDesc%3D1%26lkfm');` 

will adjust the lookup link to have the same behavior as the standard page.

**Comment by davidhabib** [comment]
thanks for the info @cdcarter .  If it is standard behavior we've always had, then I'm not going to add a hack to try to enable it.  core will undoubtedly change it over time!
