### ISSUE TITLE
JobListings #jobContainer should be .jobContainer

### ISSUE THREAD

**Issue by NevenSubotic** [SalesforceFoundation/Volunteers-for-Salesforce#391]
On the JobListingsFS.vfp, the same id "jobContainer" is given to each element. This should be class.
The error can be found here:
Line 144:  <div id="jobContainer" class="{!containerClass}">

**Comment by coriobriensfdo** [comment]
@NevenSubotic can you instead post about the issue you are having in the Volunteers for Salesforce group in the Hub? https://powerofus.force.com/_ui/core/chatter/groups/GroupProfilePage?g=0F980000000Cjjx

I asked one of our engineers to review this Issue, but they aren't sure what problem you're having as there are very few details here. When you post in the Hub, can you please be specific about what the trouble is, and what you feel should be changed (and why)? For example, what impact are you seeing (is there missing styling, unexpected behavior, etc)?

If it's determined that the code does need to be changed, we can create the issue here in GitHub and add it to the backlog.
