### ISSUE TITLE
Ability to log Volunteer Hours by users with Platform License

### ISSUE THREAD

**Issue by charles-thompson-salesforce-com** [SalesforceFoundation/Volunteers-for-Salesforce#523]
My non-profit customer has dozens of users who have no need to log into NPSP, except to log volunteer hours.  Paying for full Salesforce licenses for them is simply not an option.  The generous non-profit discount on Platform licenses is a big help.  BUT!!!  Platform license can't be used to enter Volunteer Hours because this object has a Master/Detail relationship to Volunteer Job which has a Master/Detail relationship to Campaign.  And Campaign is not available to users with only a Platform license.

The people doing data entry don't care about the campaign that a Volunteer Job is associated with.  They just want to enter hours!

Can someone on the project take this into consideration and change the M/D relationship between Volunteer Job and Campaign into a lookup?

**Comment by jamesbsfdc** [comment]
Hi @charles-thompson-salesforce-com, the existing mechanism to do this in VFS is via a personal site, which uses Salesforce Sites functionality: https://help.salesforce.com/s/articleView?id=sfdo.V4S_User_Website.htm&type=5

You can log feature requests via the IdeaExchange and I suspect there is already an idea for this: https://ideas.salesforce.com/s/search#t=All&sort=relevancy&f:@sfcategoryfull=[Nonprofit%7CVolunteers%20for%20Salesforce]

Technically it is not possible to change a master/detail field to a lookup field in a managed package. A new field would need to be created and the old one deprecated which is a significant lift because of all the associated changes that would need to happen both within the package and for existing customers.

**Comment by charles-thompson-salesforce-com** [comment]
Thank you, James.  Understood,
